name: Debugbar CI Pipeline

on: [ push, pull_request, workflow_dispatch ]

jobs:
  php-lint:
    uses: tastyigniter/workflows/.github/workflows/php-lint.yml@main
    with:
      composer: update --no-interaction --no-progress
